filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log      # Backend container'ın dışarıya mount ettiği log klasörü

    # İstersen multiline da ayarlayabilirsin, örneğin Java stack trace için:
    # multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    # multiline.negate: true
    # multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]   # Logstash servisin docker-compose içinde bu isimde olmalı ve 5044 portunda dinlemeli

logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
