input{    # veri nereden alınacak?
   file {
        path => "/logs/app.log"  # Log dosyasının yolu
        start_position => "beginning"  # Dosyayı baştan oku. Eğer dosyayı ilk kez okuyorsa, dosyanın sonundan değil başından okumaya başlar.
        sincedb_path => "/dev/null"  # Her zaman yeniden başla, okuduğunu hafızada tutma
    }
}

filter{
      if [loglevel] == "ERROR" {         # Eğer log seviyesi ERROR ise, "error" etiketi ekle
    mutate { add_tag => ["error"] }
  } else if [loglevel] == "WARN" {      # Eğer log seviyesi WARN ise, "warning" etiketi ekle
    mutate { add_tag => ["warning"] }
  } else {        # Diğer tüm log seviyeleri için "info" etiketi ekle
    mutate { add_tag => ["info"] }
  }

   grok {       # log satırını parçalar.  
  match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} - %{LOGLEVEL:loglevel} - %{GREEDYDATA:message}" } #zamanı timestamp alanına, log seviyesini loglevel alanına ve geri kalan metni message alanına kaydeder.
}

    date {       #date: timestamp alanındaki tarih bilgisini alır ve bu değeri Logstash’in dahili zaman damgası olan @timestamp alanına yazar. Böylece loglar zaman bazlı doğru sıralanır.
    match => ["timestamp", "ISO8601"]  
    target => "@timestamp"  # logstash'in dahili zaman damgası olan @timestamp alanına yazılır.
  }


}

output{  # veri nereye gönderilecek?
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]   # Elasticsearch sunucusunun adresi 
        index => "app-logs-%{+YYYY.MM.dd}"   #günlük bazlı indeks adı. Her gün için yeni bir indeks oluşturur.
    }
 
}